version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: pokeca-bank
      POSTGRES_PASSWORD: pokeca-bank
      POSTGRES_DB: pokeca-bank
    restart: always
    networks:
      - pokemon
networks:
  pokemon:
