version: '3.9'

services:
  api:
    container_name: pokeca-bank-api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3005:3000'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: pokeca-bank-db
    image: postgres:14
    ports:
      - 5433:5432
    volumes:
      - db-store:/var
    environment:
      POSTGRES_USER: pokeca-bank
      POSTGRES_PASSWORD: pokeca-bank
      POSTGRES_DB: pokeca-bank

volumes:
  db-store: